name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Set branch name var
        id: branch
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - run: echo " aaa ${{ steps.branch.short_ref }}"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build.zip build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build.zip
          tag_name: ${{ steps.branch.short_ref }}